### ISSUE TITLE
Count recoveredFundsReceiver for isRecoveryEnabled

### ISSUE THREAD

**Issue by akolotov** [zkBob/zkbob-contracts#1]
Consider to improve the logic in `isRecoveryEnabled`

https://github.com/zkBob/zkbob-contracts/blob/944bcf5adad326283d369943559c3b76c6f6331f/src/token/Recovery.sol#L89-L91

The recovery is enabled if `recoveredFundsReceiver` is set and `totalRecovery` does not exceed the limit.

**Comment by k1rill-fedoseev** [comment]
Addressed in f2a398fddee8f8903907bc739f0781c34b31232e, closing the issue
