### ISSUE TITLE
Restrict request and execute a recovery if the recovery is not enabled

### ISSUE THREAD

**Issue by akolotov** [zkBob/zkbob-contracts#2]
Consider to check that the recovery is allowed by checking recoveredFundsReceiver in `requestRecovery` and `executeRecovery`

https://github.com/zkBob/zkbob-contracts/blob/944bcf5adad326283d369943559c3b76c6f6331f/src/token/Recovery.sol#L101-L102

https://github.com/zkBob/zkbob-contracts/blob/944bcf5adad326283d369943559c3b76c6f6331f/src/token/Recovery.sol#L135-L136

**Comment by k1rill-fedoseev** [comment]
Addressed in f2a398fddee8f8903907bc739f0781c34b31232e, closing the issue
