### ISSUE TITLE
Low boundary for recoveryRequestTimelockPeriod

### ISSUE THREAD

**Issue by akolotov** [zkBob/zkbob-contracts#3]
Consider to have a low boundary for `recoveryRequestTimelockPeriod`:

https://github.com/zkBob/zkbob-contracts/blob/944bcf5adad326283d369943559c3b76c6f6331f/src/token/Recovery.sol#L81

Does it make sense to keep it on one day at least?

**Comment by k1rill-fedoseev** [comment]
Maybe. But if parameter is managed by the proxy admin, one can just upgrade the implementation with removes this restriction...

Maybe having the same proxy owner and contract owner will not work great here, so they should be different instead.

**Comment by k1rill-fedoseev** [comment]
Addressed in f2a398fddee8f8903907bc739f0781c34b31232e, closing the issue
