### ISSUE TITLE
Check for requested amount of funds to recover in requestRecovery

### ISSUE THREAD

**Issue by akolotov** [zkBob/zkbob-contracts#4]
It seems reasonable to not allow to request recovery if expected amount of total recovered funds exceeds the limit. The similar check exists in `executeRecovery`:

https://github.com/zkBob/zkbob-contracts/blob/944bcf5adad326283d369943559c3b76c6f6331f/src/token/Recovery.sol#L145-L147

**Comment by k1rill-fedoseev** [comment]
Addressed in f2a398fddee8f8903907bc739f0781c34b31232e, closing the issue
