### ISSUE TITLE
Operations limits

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-contracts#6]
# Limits

The main goal is to create an additional barrier for illicit activities and at the same time not to impair ability for regular users. Since the main feature to distinguish illicit transaction right now is the amount, it's seems reasonable to set following restictions:

1. A single operation ( deposit or withdrawal ) cannot exceed `A`
2. A single address must not deposit more than `B` during a single period of 24 hours
3. Overall sum of all of the deposits during a single period of 24 hours must not exceed `C`
4. Overall amount of tokens in the Pool must not exceed `D`

## Implementation

1. Add a mutable daily quota value to the Pool state and constructor
2. Add a map of all the addresses that have transacted that day and additional counters for overall deposits and 
3. When a user performs a transaction check that 
    1. map entry doesn't exist or contains enough quota
    2. this operation doesn't result in any excess in cumulative metrics (all daily deposits, pool overall value)
5. Process transaction
6. Reduce the quota

**Comment by k1rill-fedoseev** [comment]
Addressed in b8a7dd789fe3da1ae26a6db6981d4cab472f59fe and 5126f80d733423db734712311d9bc2451ab53396, closing the issue
