### ISSUE TITLE
[Core] Payment Link

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-contracts#65]
## What to do? 

The whole task is described in the following Notion task: https://www.notion.so/blockscout/Payment-Link-Request-Money-7af4edd96c094ef28305ce9b603c9126?pvs=4

- [x]  UI: [allow user to create a payment link and use it to make a payment](https://github.com/zkBob/zkbob-ui/issues/173)
- [x]  contracts: process swap and payment

**Comment by maikReal** [comment]
Contracts are ready
